# Factors

In [2]:
sex = c("Male", "Female", "Female", "Male", "Male")

#when a data is entered like this, vector sex is counted as string vector

In [3]:
sex = factor(sex)
sex

[1] Male   Female Female Male   Male
Levels: Female Male

In [4]:
str(sex)

 Factor w/ 2 levels "Female","Male": 2 1 1 2 2

In [5]:
levels(sex)

[1] "Female" "Male"

In [6]:
length(sex)

[1] 5

In [7]:
#Vector can be factored afterwards

smoking = c(1, 1, 2, 3, 1)
smoking = factor(smoking)
levels(smoking) = c("none", "ex-smoker", "smoker") #none: 1, ex-smoker: 2, smoker: 3
smoking

[1] none      none      ex-smoker smoker    none
Levels: none ex-smoker smoker

In [8]:
Height = c(168, 173, 160, 145, 180)
Weight = c(80, 65, 92, 53, 76)
BMI = Weight/(Height/100)^2
BMI

[1] 28.34467 21.71807 35.93750 25.20809 23.45679

In [9]:
#how to make data frame

mydata = data.frame(height = Height, weight = Weight, sex = sex, smoking = smoking)
mydata

  height weight sex    smoking
1 168    80     Male   none
2 173    65     Female none
3 160    92     Female ex-smoker
4 145    53     Male   smoker
5 180    76     Male   none

In [10]:
mydata[3,]

  height weight sex    smoking
3 160    92     Female ex-smoker

In [11]:
mydata[,1]

[1] 168 173 160 145 180

In [ ]:
#accessing to a row through row name

mydata$height

[1] 168 173 160 145 180

In [13]:
mydata[["height"]]

[1] 168 173 160 145 180

In [14]:
mydata[3]

  sex
1 Male
2 Female
3 Female
4 Male
5 Male