# NA and NULL

In [1]:
a = as.numeric("Kim") #if a non numeric value is transformed to an integer, the number changes to NA(not available)

Warning message:
"NAs introduced by coercion"

In [2]:
a

[1] NA

In [4]:
#NA is not same with NULL
#NULL means that a variable is empty

a = c()
a

NULL

In [5]:
a = c(1, 2, 3, NA, 8, NA, 10) #2 NAs in a
mean(a)

[1] NA

In [ ]:
mean(a, na.rm = T) #removing NA values from a

[1] 4.8

In [9]:
sum(is.na(a)) #counting numbers of na in a

[1] 2

In [11]:
a = c(a, NULL, 8, NULL);a #there is no error if there is null

[1]  1  2  3 NA  8 NA 10  8  8

In [12]:
(a=c(a,NA))

 [1]  1  2  3 NA  8 NA 10  8  8 NA

In [13]:
a = NULL #how to delete values in a
a

NULL

In [14]:
#the basic data set type of r is vector
#you can add values any time

a = 1:5
a = c(a, 101, 102)
b = c(a, 103)
b

[1]   1   2   3   4   5 101 102 103

In [15]:
#easy to do operations
Height = c(168, 173, 160, 145, 180)
Weight = c(80, 65, 92, 53, 76)
BMI = Weight/(Height/100)^2
BMI

[1] 28.34467 21.71807 35.93750 25.20809 23.45679

In [16]:
a = 1:10
b = c(1, -1)
a + b

 [1]  2  1  4  3  6  5  8  7 10  9

In [ ]:
b = 10
a = c = 2
b^2 + c(1, -1) * 4 * a * c #solving quadratic function

[1] 116  84

In [ ]:
#a matrix is a 2D array
#ncol means number of collums

a = matrix(1:12, ncol = 3);a

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [ ]:
#when initializing a matrix, collum is filled first

a = matrix(1:12, ncol = 3, byrow = T);a #to fill rows first, use byrow = T

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12

In [22]:
#matrix can be also made with non-numeric values

b = LETTERS[1:12];b #vector with 12 letters

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L"

In [23]:
b = matrix(b, ncol = 4);b

     [,1] [,2] [,3] [,4]
[1,] A    D    G    J
[2,] B    E    H    K
[3,] C    F    I    L

In [ ]:
b[3,2] #row 3, collum 2

[1] "F"

In [25]:
b[2, 4] #row 2, collum 4

[1] "K"

In [26]:
b[2,] #row 2

[1] "B" "E" "H" "K"

In [27]:
b[,3] #collum 3

[1] "G" "H" "I"

In [28]:
length(b)

[1] 12

In [29]:
nrow(b); ncol(b)

[1] 3

[1] 4