# 필요한 package load
- 설치가 안되어 있으면 install.packages("package name") 로 설치 후 사용

In [43]:
install.packages("tidyverse")

Installing package into 'C:/Users/82108/AppData/Local/R/win-library/4.6'
(as 'lib' is unspecified)

package 'tidyverse' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\82108\AppData\Local\Temp\Rtmp8C4HXa\downloaded_packages

In [17]:
library(dplyr)

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

In [18]:
library(haven)

In [3]:
install.packages("survey")

Installing package into 'C:/Users/82108/AppData/Local/R/win-library/4.6'
(as 'lib' is unspecified)

also installing the dependency 'mitools'

package 'mitools' successfully unpacked and MD5 sums checked
package 'survey' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\82108\AppData\Local\Temp\Rtmp8C4HXa\downloaded_packages

In [19]:
library(survey)

In [ ]:
# 현재 경로와 파일 확인
getwd()
dir()

[1] "c:/Users/82108/Dropbox/paper_work/29_구현논문/data_anaylsis_screen_obesity"

[1] "~$는 SAS 코드를 R로 변환한 버전입니다.docx"
[2] "kyrbs2023.sas7bdat"
[3] "kyrbs2024.sas7bdat"
[4] "screen_obesity_0.1.ipynb"
[5] "아래는 SAS 코드를 R로 변환한 버전입니다.docx"

In [ ]:
# dataframe display option 
- 이거 안하면 너무 많이 출력됨
options(repr.matrix.max.rows=20, repr.matrix.max.cols=200)

# 파일 불러오기
- SAS 파일 형식이므로 R에서 SAS 데이터 불러오는 package 사용해서 불러오기

In [7]:
# 1. SAS 데이터 불러오기
kyrbs2023 <- read_sas("kyrbs2023.sas7bdat")
kyrbs2024 <- read_sas("kyrbs2024.sas7bdat")

In [15]:
kyrbs2023

      OBS     mod_d       YEAR CITY CTYPE  CTYPE_SD MH       SCHOOL   STYPE
1     A100001 2024.04.09. 2023 서울 대도시 대도시   고등학교 일반계고 남학교
      STRATA  STRATA_NM          CLUSTER GROUP     W        PR_HT PR_BI PR_HD
1     2023_62 서울대_일반계고4_3 1       서울대4-3 117.7726 4     3     4
      F_BR F_FRUIT F_SWD_A
1     6    2       4
 [ reached 'max' / getOption("max.print") -- omitted 20 rows and 135 columns ]

## 2023, 2024 데이터 불러와서 두데이터 합치기

In [20]:
# 2. 2023 + 2024 합치기
ky <- bind_rows(kyrbs2023, kyrbs2024)

In [21]:
ky

       OBS     mod_d       YEAR CITY CTYPE    CTYPE_SD MH       SCHOOL
1      A100001 2024.04.09. 2023 서울 대도시   대도시   고등학교 일반계고
       STYPE    STRATA  STRATA_NM            CLUSTER GROUP     W        PR_HT
1      남학교   2023_62 서울대_일반계고4_3   1       서울대4-3 117.7726 4
       PR_BI PR_HD F_BR F_FRUIT F_SWD_A
1      3     4     6    2       4
 [ reached 'max' / getOption("max.print") -- omitted 20 rows and 181 columns ]

In [ ]:
# 컬럼 이름 확인
# 변수 설명서에서 컬럼이 먼지 확인할 것
ky %>% colnames()

 [1] "OBS"       "mod_d"     "YEAR"      "CITY"      "CTYPE"     "CTYPE_SD"
 [7] "MH"        "SCHOOL"    "STYPE"     "STRATA"    "STRATA_NM" "CLUSTER"
[13] "GROUP"     "W"         "PR_HT"     "PR_BI"     "PR_HD"     "F_BR"
[19] "F_FRUIT"   "F_SWD_A"
 [ reached 'max' / getOption("max.print") -- omitted 190 entries ]

In [41]:
colnames(ky)

 [1] "OBS"       "mod_d"     "YEAR"      "CITY"      "CTYPE"     "CTYPE_SD"
 [7] "MH"        "SCHOOL"    "STYPE"     "STRATA"    "STRATA_NM" "CLUSTER"
[13] "GROUP"     "W"         "PR_HT"     "PR_BI"     "PR_HD"     "F_BR"
[19] "F_FRUIT"   "F_SWD_A"
 [ reached 'max' / getOption("max.print") -- omitted 190 entries ]

In [ ]:
# 컬럼 이름을, 로 구분해서 출력하는 방법
# 나중에 복붙할때 유용
cat(names(ky), sep = ", ")

OBS, mod_d, YEAR, CITY, CTYPE, CTYPE_SD, MH, SCHOOL, STYPE, STRATA, STRATA_NM, CLUSTER, GROUP, W, PR_HT, PR_BI, PR_HD, F_BR, F_FRUIT, F_SWD_A, F_FASTFOOD, F_EDU, F_WAT, PA_TOT, PA_VIG_D, PA_MSC, PA_SWD_S, PA_SWD_N, PA_SWK_S, PA_SWK_N, HT, WT, WC_MN, M_STR, M_STR_RS, M_SLP_EN, M_SLP_HR, M_SLP_MM, M_WK_HR, M_WK_MM, M_SLP_HR_K, M_SLP_MM_K, M_WK_HR_K, M_WK_MM_K, M_SAD, M_SUI_CON, M_SUI_PLN, M_SUI_ATT, M_LON, M_GAD_1, M_GAD_2, M_GAD_3, M_GAD_4, M_GAD_5, M_GAD_6, M_GAD_7, O_BR_FQ, O_BR_S, O_SLNT, O_SYMP1, O_SYMP1_1, O_SYMP2, O_SYMP3, O_SYMP4, HW_SPML_S, HW_SPRM_S, HW_SPML_H, HW_SPRM_H, HW_SPGO_H, HW_EDU, I_SB_FR, I_SB_BK, I_SB_EX, I_SCH_TRT, I_SCH_ED1, I_SCH_ED2, I_SCH_ED3, I_SCH_ED4, I_SCH_ED5, V_TRT, AC_LT, AC_FAGE, AC_DAYS, AC_AMNT, AC_DRUNK, AC_ACCESS, TC_LT, TC_FAGE, TC_DAYS, TC_DAGE, TC_AMNT, TC_EC_LT, TC_EC_MN, TC_HTP_LT, TC_HTP_MN, TC_HTP_AMNT, TC_ACCESS, TC_QT_YR, TC_SND_H, TC_SND_P, SEX, S_SI, S_CONT, S_CONT_M, S_EDU, DR_HAB_PUR, AS_DG_LT, AS_DG_YR, AS_TRT, AS_ABS, RH_DG_LT, RH_DG_YR, ECZ_DG_LT, ECZ_DG_YR, INT_SPWD, INT_SPWD_TM, INT_SPWK, INT_SPWK_TM, INT_SP_OU_1, INT_SP_OU_2, INT_SP_OU_3, INT_SP_OU_4, INT_SP_OU_5, INT_SP_OU_6, INT_SP_OU_7, INT_SP_OU_8, INT_SP_OU_9, INT_SP_OU_10, AGE, AGE_M, E_S_RCRD, E_SES, E_RES, E_AID, GRADE, A_FM, E_FM_F_1, E_FM_SF_2, E_FM_M_3, E_FM_SM_4, E_FM_GF_5, E_FM_GM_6, E_FM_OBS_7, E_FM_YBS_8, E_FM_NO_9, E_LT_F, E_LT_SF, E_LT_M, E_LT_SM, E_EDU_F, E_KRN_F, E_BORN_F, E_EDU_M, E_KRN_M, E_BORN_M, F_CAFF_A, I_HM_MOT, I_HM_BICY, I_SCH, I_EAR_TRT, AC_PLC_1, AC_PLC_2, AC_PLC_3, AC_PLC_4, AC_PLC_5, AC_PLC_6, AC_EDU, AC_SND_1, AC_SND_2, AC_SND_3, AC_SND_4, AC_ALLOW, AC_AD_NO_1, AC_AD_NO_2, AC_AD_NO_3, AC_AD_NO_4, AC_AD_NO_5, AC_AD_NO_6, AC_AD_NO_7, AC_AD_NO_8, AC_POP, TC_EC_FAGE, TC_EC_DAGE, TC_HTP_FAGE, TC_HTP_DAGE, TC_PLC, TC_GET_M, TC_AD_NO_1, TC_AD_TV_2, TC_AD_RD_3, TC_AD_NS_4, TC_AD_IT_5, TC_AD_NP_6, TC_AD_PB_7, TC_TAD_NO_1, TC_TAD_NO_2, TC_TAD_NO_3, TC_TAD_NO_4, TC_TAD_NO_5, TC_SND_S, TC_EDU, TC_CSN, TC_CSF, TC_CSM, TC_CSBS, TC_CSGFM, TC_CSA, TC_CSDK, TC_CSBF, S_FAGE

## missing 값 확인

In [34]:
na.count = apply(ky,2, function(x) sum(is.na(x)))

In [38]:
na.count[na.count>0]

      PR_HD    PA_SWD_S    PA_SWD_N    PA_SWK_S    PA_SWK_N          HT
      54653        2132        2132        2643        2643        2893
         WT    M_STR_RS    M_SLP_HR    M_SLP_MM     M_WK_HR     M_WK_MM
       2893       54653        8027        8027        8027        8027
  HW_SPGO_H     AC_FAGE     TC_FAGE     TC_DAGE      AS_TRT      AS_ABS
      54653         124         122          62       54653       54653
INT_SPWD_TM INT_SPWK_TM
       3344        3394
 [ reached 'max' / getOption("max.print") -- omitted 72 entries ]

# 변수 생성

In [42]:
a5 <- ky %>%
  mutate(
    k = HT / 100,
    bmi = round(wt / (k * k), 9),

    pct05 = case_when(
      sex == 1 & age_m == 144 ~ 15.5,
      sex == 1 & age_m == 145 ~ 15.6,
      sex == 1 & age_m == 146 ~ 15.6,
      sex == 1 & age_m >= 147 & age_m <= 227 ~ 17.0,
      sex == 2 & age_m == 144 ~ 15.3,
      sex == 2 & age_m == 145 ~ 15.3,
      sex == 2 & age_m == 146 ~ 15.4,
      sex == 2 & age_m >= 147 & age_m <= 227 ~ 16.5,
      TRUE ~ NA_real_
    ),

    pct85 = case_when(
      sex == 1 & age_m == 144 ~ 23.0,
      sex == 1 & age_m == 145 ~ 23.0,
      sex == 1 & age_m == 146 ~ 23.1,
      sex == 1 & age_m >= 147 & age_m <= 227 ~ 24.5,
      sex == 2 & age_m == 144 ~ 22.1,
      sex == 2 & age_m == 145 ~ 22.2,
      sex == 2 & age_m == 146 ~ 22.2,
      sex == 2 & age_m >= 147 & age_m <= 227 ~ 23.5,
      TRUE ~ NA_real_
    ),

    pct95 = case_when(
      sex == 1 & age_m == 144 ~ 25.1,
      sex == 1 & age_m == 145 ~ 25.1,
      sex == 1 & age_m == 146 ~ 25.2,
      sex == 1 & age_m >= 147 & age_m <= 227 ~ 26.5,
      sex == 2 & age_m == 144 ~ 24.1,
      sex == 2 & age_m == 145 ~ 24.2,
      sex == 2 & age_m == 146 ~ 24.2,
      sex == 2 & age_m >= 147 & age_m <= 227 ~ 25.5,
      TRUE ~ NA_real_
    ),

    g_bmi = case_when(
      !is.na(bmi) & !is.na(pct95) & bmi >= pct95 ~ 4,
      !is.na(bmi) & !is.na(pct85) & !is.na(pct95) & bmi >= pct85 & bmi < pct95 ~ 3,
      !is.na(bmi) & !is.na(pct05) & !is.na(pct85) & bmi >= pct05 & bmi < pct85 ~ 2,
      !is.na(bmi) & !is.na(pct05) & bmi < pct05 ~ 1,
      TRUE ~ NA_real_
    ),

    sp_wd_hr = INT_SPWD_TM / 60,
    sp_wk_hr = INT_SPWK_TM / 60,
    sp_avg = (sp_wd_hr * 5 + sp_wk_hr * 2) / 7,

    time = case_when(
      sp_avg < 2 ~ 1,
      sp_avg >= 2 & sp_avg < 4 ~ 2,
      sp_avg >= 4 & sp_avg < 6 ~ 3,
      sp_avg >= 6 ~ 4,
      TRUE ~ NA_real_
    ),

    region = case_when(
      ctype == "군지역" ~ 2,
      ctype %in% c("대도시", "중소도시") ~ 1,
      TRUE ~ NA_real_
    ),

    smoking1 = if_else(TC_DAYS %in% c(1, 9999) | is.na(TC_DAYS), 0, 1),
    smoking2 = if_else(TC_EC_MN %in% c(1, 9999) | is.na(TC_EC_MN), 0, 1),
    smoking3 = if_else(TC_HTP_MN %in% c(1, 9999) | is.na(TC_HTP_MN), 0, 1),
    smoking = if_else(smoking1 == 1 | smoking2 == 1 | smoking3 == 1, 1, 0),

    edu = case_when(
      E_S_RCRD %in% c(1, 2) ~ 1,
      E_S_RCRD == 3 ~ 2,
      E_S_RCRD %in% c(4, 5) ~ 3,
      TRUE ~ NA_real_
    ),

    eco = case_when(
      E_SES %in% c(1, 2) ~ 1,
      E_SES == 3 ~ 2,
      E_SES %in% c(4, 5) ~ 3,
      TRUE ~ NA_real_
    ),

    stress = if_else(M_STR %in% c(1, 2), 1, 0),
    depress = if_else(M_SAD == 2, 1, 0),

    drinking = if_else(AC_DAYS %in% c(1, 9999) | is.na(AC_DAYS), 0, 1),

    age_g = case_when(
      age %in% c(12, 13, 14) ~ 1,
      age %in% c(15, 16, 17, 18) ~ 2,
      TRUE ~ NA_real_
    )
  ) %>%
  filter(year %in% c(2023, 2024)) %>%
  select(
    year, age_g, sex, region,
    g_bmi, time,
    smoking, drinking,
    edu, eco,
    stress, depress,
    w, cluster, strata
  ) %>%
  filter(
    !is.na(age_g),
    !is.na(g_bmi),
    !is.na(edu),
    !is.na(eco)
  ) %>%
  mutate(
    obese = case_when(
      g_bmi %in% c(1, 2, 3) ~ 0,
      g_bmi == 4 ~ 1,
      TRUE ~ NA_real_
    )
  )

ERROR: Error in `mutate()`:
ℹ In argument: `bmi = round(wt/(k * k), 9)`.
Caused by error:
! object 'wt' not found